[build]
  publish = "mockup-react/dist"
  command = "cd mockup-react && npm install && npx vite build"

[build.environment]
  NODE_VERSION = "20"

# SPA redirect for all routes including admin
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200